### ISSUE TITLE
Is this "compose" actually? ^.^

### ISSUE THREAD

**Issue by hasparus** [adhrinae/ts-react-parcel#3]
https://github.com/adhrinae/ts-react-parcel/blob/b6b4a7389794a0e88faff02ee9d12076a300a8cf/src/utilities/compose.ts#L4

**Comment by adhrinae** [comment]
Hi. I agree with what you think. This function actually might not works as we know in functional programming concepts.

Usually `compose` function works like this.

```js
const compose  = (...fns) => arg => fns.reduceRight((result, fn) => fn(result), arg)
compose(
  x => x * 10,
  x => x + 3,
)(2)
// 50
```

Technically in this repo, `compose` utility function would be called `composeTogglerProps`. You can see [the usage here](https://github.com/adhrinae/ts-react-parcel/blob/b6b4a7389794a0e88faff02ee9d12076a300a8cf/src/components/Toggle.tsx#L70).

I should rename it. and Feel free to PR if you have a better name for this function.
Thanks for your feedback.

**Comment by hasparus** [comment]
Thanks for a reply. :) Really cool starter and clean code. I feel like you did a little bit of redundant typing with `_reset(): void` because it can be interpolated, but it's really nice.

Frankly speaking I have totally no idea for better name. `makeCallAll` sounds pretty bad. Maybe `joinFuncs`?

**Comment by adhrinae** [comment]
Yeah, I should refactor the whole codebase since I wrote this code when I had no solid understanding of Typescript.

I am thinking to rewrite this example with the new context API in React 16.3

I will apply the better name for `compose` function at that time, or it might be removed :)
